from __future__ import annotations

import ast
import copy
import io
import re
import tokenize
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final, cast


@dataclass(frozen=True)
class SemanticModelAlias:
    """Describe a stable public model name for equivalent generated classes."""

    canonical: str
    members: tuple[str, ...]
    extra_aliases: tuple[str, ...] = ()
    minimum_members: int = 2
    emit_compatibility_aliases: bool = True


@dataclass(frozen=True)
class _ClassInfo:
    name: str
    node: ast.ClassDef

    @property
    def start_line(self) -> int:
        return self.node.lineno

    @property
    def end_line(self) -> int:
        return self.node.end_lineno or self.node.lineno


@dataclass(frozen=True)
class _AppliedGroup:
    group: SemanticModelAlias
    primary: str
    existing_members: tuple[str, ...]


@dataclass(frozen=True)
class _RewritePlan:
    replacements: dict[str, str]
    removed_classes: set[str]
    aliases: dict[str, str]
    applied_groups: tuple[_AppliedGroup, ...]


class _AnnotationCanonicalizer(ast.NodeTransformer):
    def __init__(self, replacements: Mapping[str, str]) -> None:
        self._replacements = replacements

    def visit_Name(self, node: ast.Name) -> ast.Name:  # noqa: N802
        replacement = self._replacements.get(node.id)
        if replacement is None:
            return node
        return ast.copy_location(ast.Name(id=replacement, ctx=node.ctx), node)


def apply_semantic_model_aliases(
    description_file: str | Path,
    groups: Sequence[SemanticModelAlias],
    common_file: str | Path | None = None,
    common_import: str | None = None,
) -> None:
    """Collapse equivalent generated models and emit backward-compatible TypeAlias names.

    Args:
        description_file: Python description module generated by datamodel-code-generator.
        groups: Stable-name policies ordered from leaves to parents. For example, collapse asset
            classes before price classes that reference those assets.
        common_file: Optional module path that should receive the canonical model classes.
        common_import: Import path used by the description module for models written to common_file.
            Set SemanticModelAlias.emit_compatibility_aliases to false when removed generated names should fail.
    """
    if (common_file is None) != (common_import is None):
        raise ValueError("common_file and common_import must be provided together.")

    description_path = description_file if isinstance(description_file, Path) else Path(description_file)
    source = description_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(description_path))
    classes = _collect_classes(tree)
    existing_aliases = _collect_type_aliases(tree)

    plan = _prepare_rewrite(groups, classes)
    if not plan.replacements and not plan.aliases:
        return

    common_model_names: set[str] = set()
    common_removed_classes: set[str] = set()
    if common_file is not None and common_import is not None:
        common_path = common_file if isinstance(common_file, Path) else Path(common_file)
        common_model_names = _write_common_models(source, classes, plan, common_path)
        common_removed_classes = _classes_moved_to_common(plan.applied_groups, classes, common_model_names)

    rewritten = _rewrite_source(source, classes, plan.replacements, plan.removed_classes | common_removed_classes)
    rewritten = _ensure_typealias_import(rewritten)
    if common_import is not None:
        rewritten = _ensure_common_model_import(rewritten, common_import, common_model_names)
    rewritten = _insert_alias_block(rewritten, plan.aliases, existing_aliases)
    description_path.write_text(rewritten, encoding="utf-8")


def _collect_classes(tree: ast.Module) -> dict[str, _ClassInfo]:
    return {
        node.name: _ClassInfo(node.name, node)
        for node in tree.body
        if isinstance(node, ast.ClassDef) and _is_struct_model(node)
    }


def _is_struct_model(node: ast.ClassDef) -> bool:
    return any(ast.unparse(base) == "Struct" for base in node.bases)


def _collect_type_aliases(tree: ast.Module) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AnnAssign):
            continue
        if not isinstance(node.target, ast.Name):
            continue
        if ast.unparse(node.annotation) != "TypeAlias" or node.value is None:
            continue
        aliases[node.target.id] = ast.unparse(node.value)
    return aliases


def _prepare_rewrite(
    groups: Sequence[SemanticModelAlias],
    classes: Mapping[str, _ClassInfo],
) -> _RewritePlan:
    replacements: dict[str, str] = {}
    removed_classes: set[str] = set()
    aliases: dict[str, str] = {}
    applied_groups: list[_AppliedGroup] = []

    for group in groups:
        existing_members = tuple(member for member in group.members if member in classes)
        canonical_exists = group.canonical in classes

        if not existing_members and not canonical_exists:
            continue
        if len(existing_members) < group.minimum_members and not canonical_exists:
            continue

        primary = group.canonical if canonical_exists else existing_members[0]
        group_replacements = dict.fromkeys(existing_members, group.canonical)

        if len(existing_members) > 1 and not _group_has_single_shape(
            existing_members, classes, replacements | group_replacements
        ):
            continue

        replacements.update(group_replacements)

        if group.emit_compatibility_aliases and primary != group.canonical:
            aliases[primary] = group.canonical

        for member in existing_members:
            if member == primary:
                continue
            removed_classes.add(member)
            if group.emit_compatibility_aliases:
                aliases[member] = group.canonical

        for alias in group.extra_aliases:
            if alias != group.canonical:
                aliases[alias] = group.canonical

        applied_groups.append(_AppliedGroup(group, primary, existing_members))

    return _RewritePlan(replacements, removed_classes, aliases, tuple(applied_groups))


def _group_has_single_shape(
    members: tuple[str, ...],
    classes: Mapping[str, _ClassInfo],
    replacements: Mapping[str, str],
) -> bool:
    signatures = {_field_signature(classes[member].node, replacements) for member in members if member in classes}
    return len(signatures) == 1


def _field_signature(
    class_node: ast.ClassDef,
    replacements: Mapping[str, str],
) -> tuple[tuple[str, str, str | None], ...]:
    fields: list[tuple[str, str, str | None]] = []
    for statement in class_node.body:
        if not isinstance(statement, ast.AnnAssign):
            continue
        if not isinstance(statement.target, ast.Name):
            continue

        fields.append(
            (
                statement.target.id,
                _canonical_annotation(statement.annotation, replacements),
                ast.unparse(statement.value) if statement.value is not None else None,
            )
        )
    return tuple(fields)


def _canonical_annotation(annotation: ast.expr, replacements: Mapping[str, str]) -> str:
    annotation_copy = copy.deepcopy(annotation)
    canonicalized = _AnnotationCanonicalizer(replacements).visit(ast.fix_missing_locations(annotation_copy))
    return ast.unparse(canonicalized)


def _write_common_models(
    source: str,
    classes: Mapping[str, _ClassInfo],
    plan: _RewritePlan,
    common_file: Path,
) -> set[str]:
    common_source = common_file.read_text(encoding="utf-8") if common_file.exists() else ""
    common_classes = _collect_classes(ast.parse(common_source)) if common_source else {}
    candidates = _collect_common_candidates(source, classes, common_classes, plan)
    accepted_names = _filter_common_candidates(candidates, common_classes)
    blocks_to_append = {
        name: candidate.source_block
        for name, candidate in candidates.items()
        if name in accepted_names and name not in common_classes
    }

    if blocks_to_append:
        common_file.parent.mkdir(parents=True, exist_ok=True)
        common_source = _ensure_common_header(common_source, source)
        common_source = (
            common_source.rstrip()
            + "\n\n"
            + "\n\n".join(blocks_to_append[name].strip() for name in accepted_names if name in blocks_to_append)
            + "\n"
        )
        common_file.write_text(common_source, encoding="utf-8")

    return accepted_names


@dataclass(frozen=True)
class _CommonCandidate:
    source_block: str
    dependencies: set[str]


def _collect_common_candidates(
    source: str,
    classes: Mapping[str, _ClassInfo],
    common_classes: Mapping[str, _ClassInfo],
    plan: _RewritePlan,
) -> dict[str, _CommonCandidate]:
    candidates: dict[str, _CommonCandidate] = {}
    for applied_group in plan.applied_groups:
        canonical = applied_group.group.canonical
        primary = applied_group.primary
        if primary not in classes:
            continue

        source_node = classes[primary].node
        if canonical in common_classes and not _same_shape_as_common(
            source_node, common_classes[canonical].node, plan.replacements
        ):
            continue

        source_block = _class_source(source, classes[primary])
        candidates[canonical] = _CommonCandidate(
            _replace_code_identifiers(source_block, plan.replacements),
            _class_dependencies(source_node, plan.replacements),
        )

    return candidates


def _same_shape_as_common(
    source_node: ast.ClassDef,
    common_node: ast.ClassDef,
    replacements: Mapping[str, str],
) -> bool:
    return _field_signature(source_node, replacements) == _field_signature(common_node, {})


_COMMON_SAFE_NAMES: Final[set[str]] = {
    "Any",
    "Literal",
    "Meta",
    "None",
    "Struct",
    "TypeAlias",
    "UNSET",
    "UnsetType",
    "bool",
    "bytes",
    "dict",
    "field",
    "float",
    "frozenset",
    "int",
    "list",
    "set",
    "str",
    "tuple",
}


def _filter_common_candidates(
    candidates: Mapping[str, _CommonCandidate],
    common_classes: Mapping[str, _ClassInfo],
) -> set[str]:
    accepted = set(candidates)
    existing_common_names = set(common_classes)

    changed = True
    while changed:
        changed = False
        available_names = existing_common_names | accepted
        for name in tuple(accepted):
            dependencies = candidates[name].dependencies
            missing_dependencies = dependencies - available_names
            if missing_dependencies:
                accepted.remove(name)
                changed = True

    return accepted


def _class_dependencies(class_node: ast.ClassDef, replacements: Mapping[str, str]) -> set[str]:
    dependencies: set[str] = set()
    for statement in class_node.body:
        if not isinstance(statement, ast.AnnAssign):
            continue
        for expression in (statement.annotation, statement.value):
            if expression is None:
                continue
            for node in ast.walk(expression):
                if isinstance(node, ast.Name):
                    dependencies.add(replacements.get(node.id, node.id))

    class_name = replacements.get(class_node.name, class_node.name)
    return {
        dependency for dependency in dependencies if dependency not in _COMMON_SAFE_NAMES and dependency != class_name
    }


def _class_source(source: str, class_info: _ClassInfo) -> str:
    return "".join(source.splitlines(keepends=True)[class_info.start_line - 1 : class_info.end_line])


def _classes_moved_to_common(
    applied_groups: Sequence[_AppliedGroup],
    classes: Mapping[str, _ClassInfo],
    common_model_names: set[str],
) -> set[str]:
    removed_classes: set[str] = set()
    for applied_group in applied_groups:
        if applied_group.group.canonical not in common_model_names:
            continue
        removed_classes.update(member for member in applied_group.existing_members if member in classes)
        if applied_group.group.canonical in classes:
            removed_classes.add(applied_group.group.canonical)
    return removed_classes


def _rewrite_source(
    source: str,
    classes: Mapping[str, _ClassInfo],
    replacements: Mapping[str, str],
    removed_classes: set[str],
) -> str:
    lines = source.splitlines(keepends=True)
    removed_ranges = [(classes[name].start_line, classes[name].end_line) for name in removed_classes if name in classes]

    kept_lines = [
        line for line_number, line in enumerate(lines, start=1) if not _line_is_removed(line_number, removed_ranges)
    ]
    return _replace_code_identifiers("".join(kept_lines), replacements)


def _line_is_removed(line_number: int, ranges: Sequence[tuple[int, int]]) -> bool:
    return any(start <= line_number <= end for start, end in ranges)


def _replace_code_identifiers(source: str, replacements: Mapping[str, str]) -> str:
    if not replacements:
        return source

    replaced_tokens: list[tokenize.TokenInfo] = []
    for token_info in tokenize.generate_tokens(io.StringIO(source).readline):
        if token_info.type == tokenize.NAME and token_info.string in replacements:
            token_info = tokenize.TokenInfo(
                token_info.type,
                replacements[token_info.string],
                token_info.start,
                token_info.end,
                token_info.line,
            )
        replaced_tokens.append(token_info)

    return cast(str, tokenize.untokenize(replaced_tokens))


def _ensure_typealias_import(source: str) -> str:
    if re.search(r"^from typing import .*?\bTypeAlias\b", source, flags=re.MULTILINE):
        return source

    typing_import = re.search(r"^from typing import (?P<imports>.+)$", source, flags=re.MULTILINE)
    if typing_import:
        imports = typing_import.group("imports")
        replacement = f"from typing import {imports}, TypeAlias"
        return source[: typing_import.start()] + replacement + source[typing_import.end() :]

    lines = source.splitlines(keepends=True)
    insert_index = 0
    for index, line in enumerate(lines):
        if line.startswith("from __future__ import "):
            insert_index = index + 1
            continue
        if insert_index and line.strip() == "":
            insert_index = index + 1
            continue
        if insert_index:
            break

    lines.insert(insert_index, "from typing import TypeAlias\n")
    return "".join(lines)


def _ensure_common_model_import(source: str, common_import: str, names: set[str]) -> str:
    if not names:
        return source

    import_pattern = re.compile(
        rf"^from {re.escape(common_import)} import (?P<imports>[A-Za-z0-9_, ]+)$",
        flags=re.MULTILINE,
    )
    match = import_pattern.search(source)
    if match:
        existing_names = {name.strip() for name in match.group("imports").split(",") if name.strip()}
        imports = ", ".join(sorted(existing_names | names))
        return source[: match.start()] + f"from {common_import} import {imports}" + source[match.end() :]

    lines = source.splitlines(keepends=True)
    insertion_index = _find_import_insertion_index(lines)
    lines.insert(insertion_index, f"from {common_import} import {', '.join(sorted(names))}\n")
    return "".join(lines)


def _ensure_common_header(common_source: str, source: str) -> str:
    header_lines = _extract_import_header(source)
    if not common_source:
        return "".join(header_lines).rstrip() + "\n"

    lines = common_source.splitlines(keepends=True)
    insertion_index = _find_import_insertion_index(lines)
    missing_header_lines = [line for line in header_lines if line.strip() and line not in lines]
    if not missing_header_lines:
        return common_source

    lines[insertion_index:insertion_index] = missing_header_lines
    return "".join(lines)


def _extract_import_header(source: str) -> list[str]:
    header_lines: list[str] = []
    for line in source.splitlines(keepends=True):
        stripped = line.strip()
        if line.startswith("from __future__ import ") or line.startswith("from ") or line.startswith("import "):
            header_lines.append(line)
            continue
        if line.startswith("class ") or _DESCRIPTION_DICT_PATTERN.match(line):
            break
        if header_lines and not stripped:
            header_lines.append(line)

    if not any(line.startswith("from __future__ import annotations") for line in header_lines):
        header_lines.insert(0, "from __future__ import annotations\n")

    return header_lines


def _find_import_insertion_index(lines: Sequence[str]) -> int:
    insert_index = 0
    in_import_section = False
    for index, line in enumerate(lines):
        stripped = line.strip()
        if line.startswith("from ") or line.startswith("import "):
            in_import_section = True
            insert_index = index + 1
            continue
        if in_import_section and not stripped:
            insert_index = index + 1
            continue
        if in_import_section:
            break
    return insert_index


def _insert_alias_block(source: str, aliases: Mapping[str, str], existing_aliases: Mapping[str, str]) -> str:
    alias_block = _render_alias_block(aliases, existing_aliases)
    if not alias_block:
        return source

    lines = source.splitlines(keepends=True)
    insertion_index = _find_description_dict_line(lines)
    lines[insertion_index:insertion_index] = alias_block
    return "".join(lines)


def _render_alias_block(aliases: Mapping[str, str], existing_aliases: Mapping[str, str]) -> list[str]:
    lines = ["\n# Stable public aliases for equivalent generated models.\n"]
    aliases_written = False

    for alias, target in aliases.items():
        if existing_aliases.get(alias) == target:
            continue
        lines.append(f"{alias}: TypeAlias = {target}\n")
        aliases_written = True

    if not aliases_written:
        return []

    lines.append("\n")
    return lines


_DESCRIPTION_DICT_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*_description = \{")


def _find_description_dict_line(lines: Sequence[str]) -> int:
    for index, line in enumerate(lines):
        if _DESCRIPTION_DICT_PATTERN.match(line):
            return index
    return len(lines)
