from __future__ import annotations

import ast
import copy
import io
import re
import tokenize
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Final, cast


@dataclass(frozen=True)
class SemanticModelAlias:
    """Describe a stable public model name for equivalent generated classes."""

    canonical: str
    members: tuple[str, ...]
    extra_aliases: tuple[str, ...] = ()
    minimum_members: int = 2


@dataclass(frozen=True)
class _ClassInfo:
    name: str
    node: ast.ClassDef

    @property
    def start_line(self) -> int:
        return self.node.lineno

    @property
    def end_line(self) -> int:
        return self.node.end_lineno or self.node.lineno


class _AnnotationCanonicalizer(ast.NodeTransformer):
    def __init__(self, replacements: Mapping[str, str]) -> None:
        self._replacements = replacements

    def visit_Name(self, node: ast.Name) -> ast.Name:  # noqa: N802
        replacement = self._replacements.get(node.id)
        if replacement is None:
            return node
        return ast.copy_location(ast.Name(id=replacement, ctx=node.ctx), node)


def apply_semantic_model_aliases(description_file: str | Path, groups: Sequence[SemanticModelAlias]) -> None:
    """Collapse equivalent generated models and emit backward-compatible TypeAlias names.

    Args:
        description_file: Python description module generated by datamodel-code-generator.
        groups: Stable-name policies ordered from leaves to parents. For example, collapse asset
            classes before price classes that reference those assets.
    """
    description_path = description_file if isinstance(description_file, Path) else Path(description_file)
    source = description_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(description_path))
    classes = _collect_classes(tree)
    existing_aliases = _collect_type_aliases(tree)

    replacements, removed_classes, aliases = _prepare_rewrite(groups, classes)
    if not replacements and not aliases:
        return

    rewritten = _rewrite_source(source, classes, replacements, removed_classes)
    rewritten = _ensure_typealias_import(rewritten)
    rewritten = _insert_alias_block(rewritten, aliases, existing_aliases)
    description_path.write_text(rewritten, encoding="utf-8")


def _collect_classes(tree: ast.Module) -> dict[str, _ClassInfo]:
    return {
        node.name: _ClassInfo(node.name, node)
        for node in tree.body
        if isinstance(node, ast.ClassDef) and _is_struct_model(node)
    }


def _is_struct_model(node: ast.ClassDef) -> bool:
    return any(ast.unparse(base) == "Struct" for base in node.bases)


def _collect_type_aliases(tree: ast.Module) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.AnnAssign):
            continue
        if not isinstance(node.target, ast.Name):
            continue
        if ast.unparse(node.annotation) != "TypeAlias" or node.value is None:
            continue
        aliases[node.target.id] = ast.unparse(node.value)
    return aliases


def _prepare_rewrite(
    groups: Sequence[SemanticModelAlias],
    classes: Mapping[str, _ClassInfo],
) -> tuple[dict[str, str], set[str], dict[str, str]]:
    replacements: dict[str, str] = {}
    removed_classes: set[str] = set()
    aliases: dict[str, str] = {}

    for group in groups:
        existing_members = tuple(member for member in group.members if member in classes)
        canonical_exists = group.canonical in classes

        if not existing_members and not canonical_exists:
            continue
        if len(existing_members) < group.minimum_members and not canonical_exists:
            continue

        primary = group.canonical if canonical_exists else existing_members[0]
        group_replacements = dict.fromkeys(existing_members, group.canonical)

        if len(existing_members) > 1 and not _group_has_single_shape(
            existing_members, classes, replacements | group_replacements
        ):
            continue

        replacements.update(group_replacements)

        if primary != group.canonical:
            aliases[primary] = group.canonical

        for member in existing_members:
            if member == primary:
                continue
            removed_classes.add(member)
            aliases[member] = group.canonical

        for alias in group.extra_aliases:
            if alias != group.canonical:
                aliases[alias] = group.canonical

    return replacements, removed_classes, aliases


def _group_has_single_shape(
    members: tuple[str, ...],
    classes: Mapping[str, _ClassInfo],
    replacements: Mapping[str, str],
) -> bool:
    signatures = {_field_signature(classes[member].node, replacements) for member in members if member in classes}
    return len(signatures) == 1


def _field_signature(
    class_node: ast.ClassDef,
    replacements: Mapping[str, str],
) -> tuple[tuple[str, str, str | None], ...]:
    fields: list[tuple[str, str, str | None]] = []
    for statement in class_node.body:
        if not isinstance(statement, ast.AnnAssign):
            continue
        if not isinstance(statement.target, ast.Name):
            continue

        fields.append(
            (
                statement.target.id,
                _canonical_annotation(statement.annotation, replacements),
                ast.unparse(statement.value) if statement.value is not None else None,
            )
        )
    return tuple(fields)


def _canonical_annotation(annotation: ast.expr, replacements: Mapping[str, str]) -> str:
    annotation_copy = copy.deepcopy(annotation)
    canonicalized = _AnnotationCanonicalizer(replacements).visit(ast.fix_missing_locations(annotation_copy))
    return ast.unparse(canonicalized)


def _rewrite_source(
    source: str,
    classes: Mapping[str, _ClassInfo],
    replacements: Mapping[str, str],
    removed_classes: set[str],
) -> str:
    lines = source.splitlines(keepends=True)
    removed_ranges = [(classes[name].start_line, classes[name].end_line) for name in removed_classes if name in classes]

    kept_lines = [
        line for line_number, line in enumerate(lines, start=1) if not _line_is_removed(line_number, removed_ranges)
    ]
    return _replace_code_identifiers("".join(kept_lines), replacements)


def _line_is_removed(line_number: int, ranges: Sequence[tuple[int, int]]) -> bool:
    return any(start <= line_number <= end for start, end in ranges)


def _replace_code_identifiers(source: str, replacements: Mapping[str, str]) -> str:
    if not replacements:
        return source

    replaced_tokens: list[tokenize.TokenInfo] = []
    for token_info in tokenize.generate_tokens(io.StringIO(source).readline):
        if token_info.type == tokenize.NAME and token_info.string in replacements:
            token_info = tokenize.TokenInfo(
                token_info.type,
                replacements[token_info.string],
                token_info.start,
                token_info.end,
                token_info.line,
            )
        replaced_tokens.append(token_info)

    return cast(str, tokenize.untokenize(replaced_tokens))


def _ensure_typealias_import(source: str) -> str:
    if re.search(r"^from typing import .*?\bTypeAlias\b", source, flags=re.MULTILINE):
        return source

    typing_import = re.search(r"^from typing import (?P<imports>.+)$", source, flags=re.MULTILINE)
    if typing_import:
        imports = typing_import.group("imports")
        replacement = f"from typing import {imports}, TypeAlias"
        return source[: typing_import.start()] + replacement + source[typing_import.end() :]

    lines = source.splitlines(keepends=True)
    insert_index = 0
    for index, line in enumerate(lines):
        if line.startswith("from __future__ import "):
            insert_index = index + 1
            continue
        if insert_index and line.strip() == "":
            insert_index = index + 1
            continue
        if insert_index:
            break

    lines.insert(insert_index, "from typing import TypeAlias\n")
    return "".join(lines)


def _insert_alias_block(source: str, aliases: Mapping[str, str], existing_aliases: Mapping[str, str]) -> str:
    alias_block = _render_alias_block(aliases, existing_aliases)
    if not alias_block:
        return source

    lines = source.splitlines(keepends=True)
    insertion_index = _find_description_dict_line(lines)
    lines[insertion_index:insertion_index] = alias_block
    return "".join(lines)


def _render_alias_block(aliases: Mapping[str, str], existing_aliases: Mapping[str, str]) -> list[str]:
    lines = ["\n# Stable public aliases for equivalent generated models.\n"]
    aliases_written = False

    for alias, target in aliases.items():
        if existing_aliases.get(alias) == target:
            continue
        lines.append(f"{alias}: TypeAlias = {target}\n")
        aliases_written = True

    if not aliases_written:
        return []

    lines.append("\n")
    return lines


_DESCRIPTION_DICT_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*_description = \{")


def _find_description_dict_line(lines: Sequence[str]) -> int:
    for index, line in enumerate(lines):
        if _DESCRIPTION_DICT_PATTERN.match(line):
            return index
    return len(lines)
